name: Build Docker
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: GET Factorio image version
        shell: bash
        run: echo "FACTORIO_VERSION=$(wget -q 'https://registry.hub.docker.com/v2/repositories/factoriotools/factorio/tags?page_size=30' -O -  | jq  -r '.results[].name' | grep -E "([0-9]|\.)+" | sort | tail -n 1)" >> $GITHUB_OUTPUT
        id: factorio_version
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}
          tags: |
            type=raw,value={{branch}}-${{ steps.factorio_version.outputs.FACTORIO_VERSION }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            FACTORIO_VERSION=${{ steps.factorio_version.outputs.FACTORIO_VERSION }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64/v8
